"""add_avatar_to_tiktok_profile

Revision ID: 8cc70c788878
Revises: aec53295d1de
Create Date: 2025-04-18 22:13:22.713499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc70c788878'
down_revision: Union[str, None] = 'aec53295d1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiktok_profile', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiktok_profile', 'avatar_url')
    # ### end Alembic commands ###
