"""create_tiktokprofile_table

Revision ID: aec53295d1de
Revises: 5a287e2f4d3d
Create Date: 2025-04-16 23:26:22.360167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec53295d1de'
down_revision: Union[str, None] = '5a287e2f4d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_profile',
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('verified', sa.Integer(), nullable=True),
        sa.Column('private_account', sa.Integer(), nullable=True),
        sa.Column('region', sa.String(), nullable=True),
        sa.Column('following', sa.Integer(), nullable=True),
        sa.Column('friends', sa.Integer(), nullable=True),
        sa.Column('fans', sa.Integer(), nullable=True),
        sa.Column('heart', sa.Integer(), nullable=True),
        sa.Column('video', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_tiktok_profile_username'), 'tiktok_profile', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiktok_profile_username'), table_name='tiktok_profile')
    op.drop_table('tiktok_profile')
    # ### end Alembic commands ###
