"""add_signature_to_tiktok_profile

Revision ID: e7ac04c2751c
Revises: 8cc70c788878
Create Date: 2025-04-18 22:26:43.602731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ac04c2751c'
down_revision: Union[str, None] = '8cc70c788878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiktok_profile', sa.Column('signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiktok_profile', 'signature')
    # ### end Alembic commands ###
